name: Tag on Release Branch Merge

on:
  push:
    branches:
      - release
permissions: write-all
jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can access tags

      # Get the latest tag, if any, and handle if no tags exist
      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # Fetch all tags and get the latest one
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          
          # Check if latest_tag is empty (i.e., no tags in the repository)
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.0" # Default to v0.0.0 if no tags exist
          fi
          echo "Latest tag: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      # Extract version number and bump the patch version
      - name: Calculate new tag
        id: calculate_tag
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.tag }}"
          # Remove 'v' prefix and extract version parts
          version_without_v=${latest_tag#v}
          IFS='.' read -r -a version_parts <<< "$version_without_v"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          patch="${version_parts[2]}"

          # Bump the patch version
          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"

          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      # Create and push the new tag to the repository using GITHUB_TOKEN
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token for authentication
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create a new tag
          git tag ${{ steps.calculate_tag.outputs.new_tag }}
          
          # Push the new tag to the repository
          git push origin --tags
